## Colors configuration
# [colors.primary]
# background = "#222d32"
# foreground = "#c4c7c5"
#
# [colors.normal]
# black   = "#263640"
# red     = "#ec7875"
# green   = "#61c766"
# yellow  = "#fdd835"
# blue    = "#42a5f5"
# magenta = "#ba68c8"
# cyan    = "#4dd0e1"
# white   = "#bfbaac"
#
# [colors.bright]
# black   = "#4a697d"
# red     = "#fb8784"
# green   = "#70d675"
# yellow  = "#ffe744"
# blue    = "#51b4ff"
# magenta = "#c979d7"
# cyan    = "#5cdff0"
# white   = "#fdf6e3"
#
# TokyoNight Alacritty Colors
# Default colors
# [colors.primary]
# background = '#1a1b26'
# foreground = '#c0caf5'
#
# [colors.cursor]
# cursor = '#c0caf5'
# text = '#1a1b26'
#
# # Normal colors
# [colors.normal]
# black = '#15161e'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# # Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#ff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#db4b4b'

# Catppuccin for Alacritty  
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

# Eldritch for Alacritty  
# [colors.bright]
# black = "#7081d0"
# blue = "#a48cf2"
# cyan = "#66e4fd"
# green = "#69F8B3"
# magenta = "#FD92CE"
# red = "#f16c75"
# white = "#ffffff"
# yellow = "#f1fc79"
#
# [colors.cursor]
# cursor = "#37f499"
# text = "#f8f8f2"
#
# [colors.hints.end]
# background = "#212337"
# foreground = "#f1fc79"
#
# [colors.hints.start]
# background = "#f1fc79"
# foreground = "#212337"
#
# [colors.line_indicator]
# background = "None"
# foreground = "None"
#
# [colors.normal]
# black = "#21222c"
# blue = "#9071f4"
# cyan = "#04d1f9"
# green = "#37f499"
# magenta = "#f265b5"
# red = "#f9515d"
# white = "#ebfafa"
# yellow = "#e9f941"
#
# [colors.primary]
# background = "#212337"
# bright_foreground = "#ebfafa"
# foreground = "#ebfafa"
#
# [colors.search.focused_match]
# background = "#f16c75"
# foreground = "#212337"
#
# # [colors.search."footer.bar"]
# # background = "#212337"
# # foreground = "#ebfafa"
#
# [colors.search.matches]
# background = "#37f499"
# foreground = "#212337"
#
# [colors.selection]
# background = "#bf4f8e"
# text = "#ebfafa"
#
# [colors.vi_mode_cursor]
# cursor = "#37f499"
# text = "#f8f8f2"

# Edge for Alacritty
# Dark
# [colors.normal]
# black = "0x202023"
# red = "0xec7279"
# green = "0xa0c980"
# yellow = "0xdeb974"
# blue = "0x6cb6eb"
# magenta = "0xd38aea"
# cyan = "0x5dbbc1"
# white = "0x758094"
#
# [colors.bright]
# black = "0x535c6a"
# red = "0xec7279"
# green = "0xa0c980"
# yellow = "0xdeb974"
# blue = "0x6cb6eb"
# magenta = "0xd38aea"
# cyan = "0x5dbbc1"
# white = "0xc5cdd9"
#
# [colors.primary]
# background = "0x2c2e34"
# foreground = "0xc5cdd9"

# Aura
# [colors.normal]
# black = "0x202023"
# red = "0xec7279"
# green = "0xa0c980"
# yellow = "0xdeb974"
# blue = "0x6cb6eb"
# magenta = "0xd38aea"
# cyan = "0x5dbbc1"
# white = "0x758094"
#
# [colors.bright]
# black = "0x535c6a"
# red = "0xec7279"
# green = "0xa0c980"
# yellow = "0xdeb974"
# blue = "0x6cb6eb"
# magenta = "0xd38aea"
# cyan = "0x5dbbc1"
# white = "0xc5cdd9"
#
# [colors.primary]
# background = "0x2b2d37"
# foreground = "0xc5cdd9"

# Light
# [colors.bright]
# black = "0x4b505b"
# red = "0xd05858"
# green = "0x608e32"
# yellow = "0xbe7e05"
# blue = "0x5079be"
# magenta = "0xb05ccc"
# cyan = "0x3a8b84"
# white = "0xbac3cb"
#
# [colors.normal]
# black = "0x8790a0"
# red = "0xd05858"
# green = "0x608e32"
# yellow = "0xbe7e05"
# blue = "0x5079be"
# magenta = "0xb05ccc"
# cyan = "0x3a8b84"
# white = "0xdde2e7"
#
# [colors.primary]
# background = "0xfafafa"
# foreground = "0x4b505b"

# Neon
# [colors.normal]
# black = "0x202023"
# red = "0xec7279"
# green = "0xa0c980"
# yellow = "0xdeb974"
# blue = "0x6cb6eb"
# magenta = "0xd38aea"
# cyan = "0x5dbbc1"
# white = "0x758094"
#
# [colors.bright]
# black = "0x535c6a"
# red = "0xec7279"
# green = "0xa0c980"
# yellow = "0xdeb974"
# blue = "0x6cb6eb"
# magenta = "0xd38aea"
# cyan = "0x5dbbc1"
# white = "0xc5cdd9"
#
# [colors.primary]
# background = "0x2b2d3a"
# foreground = "0xc5cdd9"

# One Dark for Alacritty

# Default colors
# [colors.primary]
# background = '#282c34'
# foreground = '#abb2bf'
#
# # Normal colors
# [colors.normal]
# black   = '#1e2127'
# red     = '#e06c75'
# green   = '#98c379'
# yellow  = '#d19a66'
# blue    = '#61afef'
# magenta = '#c678dd'
# cyan    = '#56b6c2'
# white   = '#abb2bf'
#
# # Bright colors
# [colors.bright]
# black   = '#5c6370'
# red     = '#e06c75'
# green   = '#98c379'
# yellow  = '#d19a66'
# blue    = '#61afef'
# magenta = '#c678dd'
# cyan    = '#56b6c2'
# white   = '#ffffff'

# Cyberdream for Alacritty
# [[colors.indexed_colors]]
# color = "0xffbd5e"
# index = 16
#
# [[colors.indexed_colors]]
# color = "0xff6e5e"
# index = 17
#
# [colors.bright]
# black = "0x3c4048"
# blue = "0x5ea1ff"
# cyan = "0x5ef1ff"
# green = "0x5eff6c"
# magenta = "0xbd5eff"
# red = "0xff6e5e"
# white = "0xffffff"
# yellow = "0xf1ff5e"
#
# [colors.normal]
# black = "0x16181a"
# blue = "0x5ea1ff"
# cyan = "0x5ef1ff"
# green = "0x5eff6c"
# magenta = "0xbd5eff"
# red = "0xff6e5e"
# white = "0xffffff"
# yellow = "0xf1ff5e"
#
# [colors.primary]
# background = "0x16181a"
# foreground = "0xffffff"
#
# [colors.selection]
# background = "0x3c4048"
# foreground = "0xffffff"
